name: radio_browser_api
description: An HTTP client for Radio Browser
version: 1.0.0
homepage: https://github.com/tomassasovsky/radio-browser-api.dart.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  http: ^1.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.0
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.0.0+1
